### ISSUE TITLE
Clinical phase sorting in `Clinical Precedence` not working as expected

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3001] opened 2023-06-23 11:26 UTC
**Describe the bug**
Incorrect sorting by clinical phase in the `Clinical Precedence` widget for CHEMBL1324.

**Observed behaviour**
[CHEMBL1324](https://platform.dev.opentargets.xyz/drug/CHEMBL1324) has a CT in Early Phase I for Familial transthyretin-related amyloidosis.

This is visible in the clinical precedence widget for Tolcapone, however sorting the widget by phase does not work as expected. When ordering from low to high, the study with the lowest phase is Phase II, not the Early Phase I.
![image](https://github.com/opentargets/issues/assets/45119610/ccc5db6f-9878-48c4-86dc-0696a0de8e0f)

**Expected behaviour**
To see the cited study at the top.

**Additional context**
Clinical Precedence comes from the ChEMBL evidence. Other tables that depend on the evidence order the data correctly.

**Comment by prashantuniyal02** [comment] 2023-06-23 11:51
I think it is sorting only amongst the displayed rows. 
When you select max 100 rows, and sort by clinical phase, it correctly sorts by Clinical Phase and displays (Early Phase 1 as first row in ascending order)

![image](https://github.com/opentargets/issues/assets/122870584/d6d394bd-70f9-46a7-b7a1-69714db18018)

**Comment by prashantuniyal02** [comment] 2024-04-09 10:43
This issue is because of the table being server side paginated and not having a sort functionality
duplicate of #3160

**Closed by prashantuniyal02** 2024-04-09 10:43 UTC
Labels: Bug, Frontend, Platform
