### ISSUE TITLE
Refactor GWAS Catalog data update script

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3196] opened 2024-01-18 11:57 UTC
Currently the logic to re-fresh GWAS catalog data is in a shell script under `utils/`. This is because it was written before the airflow layer was developed. However at this point it isn't fit well with the overall design of the pipeline.

**Expectations:**

- [ ] All the logic, which is currently in `utils/update_GWAS_Catalog_data.sh` should be moved to airflwo layer. 
- [ ] The logic should also harvest and store the GWAS related metadata and stored in the manifests.
- [ ] Test run.

**Comment by prashantuniyal02** [comment] 2024-09-16 11:21
duplicate of #3241

**Closed by prashantuniyal02** 2024-09-16 11:21 UTC
Labels: Data, Gentropy
