### ISSUE TITLE
Anomaly in Drug Profile Bibliography widget in Dev

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2997] opened 2023-06-21 13:40 UTC
**Describe the bug**
We have identified a number of 'red' chips (CHEMBL IDs) in the Bibliography component for Drug Profiles.
Some examples below. 
https://platform.dev.opentargets.xyz/drug/CHEMBL1233
https://partner-platform.dev.opentargets.xyz/drug/CHEMBL122

For CHEMBL1233, for example, the "red" chip returns `object` null to API query
```

{
          "score": 0.9009292235331385,
          "id": "CHEMBL1079604",
          "object": null,
          "__typename": "Similarity"
        },

```

compared to 'blue chipped drugs'
```
{
"score": 0.9011679650897512,
          "id": "CHEMBL669",
          "object": {
            "id": "CHEMBL669",
            "name": "CYCLOBENZAPRINE",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
  },


```

<details>
  <summary>SimilarEntitiesQuery</summary>

```
query SimilarEntitiesQuery($id: String!, $ids: [String!] = [], $startYear: Int = null, $startMonth: Int = null, $endYear: Int = null, $endMonth: Int = null, $threshold: Float = 0.5, $size: Int! = 15, $entityNames: [String!] = [], $cursor: String = null) {
  drug(chemblId: $id) {
    id
    name
    similarEntities(
      additionalIds: $ids
      threshold: $threshold
      size: $size
      entityNames: $entityNames
    ) {
      score
      id
      object {
        ... on Target {
          id
          approvedSymbol
          __typename
        }
        ... on Drug {
          id
          name
          __typename
        }
        ... on Disease {
          id
          name
          __typename
        }
        __typename
      }
      __typename
    }
    literatureOcurrences(
      additionalIds: $ids
      cursor: $cursor
      startYear: $startYear
      startMonth: $startMonth
      endYear: $endYear
      endMonth: $endMonth
    ) {
      count
      earliestPubYear
      cursor
      rows {
        pmid
        pmcid
        publicationDate
        __typename
      }
      __typename
    }
    __typename
  }
}
variables
{
  "ids": [],
  "startYear": null,
  "startMonth": null,
  "endYear": null,
  "endMonth": null,
  "threshold": 0.5,
  "size": 15,
  "entityNames": [
    "disease",
    "drug",
    "target"
  ],
  "cursor": null,
  "id": "CHEMBL1233"
}
```
</details>

<details>
  <summary>Response with bugs</summary>

```
{
  "data": {
    "drug": {
      "id": "CHEMBL1233",
      "name": "CARISOPRODOL",
      "similarEntities": [
        {
          "score": 1,
          "id": "CHEMBL1233",
          "object": {
            "id": "CHEMBL1233",
            "name": "CARISOPRODOL",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9294632602629279,
          "id": "CHEMBL979",
          "object": {
            "id": "CHEMBL979",
            "name": "MEPROBAMATE",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9160909625187146,
          "id": "CHEMBL1201117",
          "object": {
            "id": "CHEMBL1201117",
            "name": "METHOCARBAMOL",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9067193969054652,
          "id": "CHEMBL1289779",
          "object": {
            "id": "CHEMBL1289779",
            "name": "ETIZOLAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9065396646905903,
          "id": "CHEMBL2105527",
          "object": {
            "id": "CHEMBL2105527",
            "name": "TETRAZEPAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9011679650897512,
          "id": "CHEMBL669",
          "object": {
            "id": "CHEMBL669",
            "name": "CYCLOBENZAPRINE",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.9009292235331385,
          "id": "CHEMBL1079604",
          "object": null,
          "__typename": "Similarity"
        },
        {
          "score": 0.9003082039050094,
          "id": "CHEMBL970",
          "object": {
            "id": "CHEMBL970",
            "name": "HALAZEPAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8957260848236265,
          "id": "CHEMBL969",
          "object": {
            "id": "CHEMBL969",
            "name": "PRAZEPAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8946871058722702,
          "id": "CHEMBL2104356",
          "object": {
            "id": "CHEMBL2104356",
            "name": "KETAZOLAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8935800882040017,
          "id": "CHEMBL1213352",
          "object": {
            "id": "CHEMBL1213352",
            "name": "PINAZEPAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8933270445640878,
          "id": "CHEMBL1213351",
          "object": {
            "id": "CHEMBL1213351",
            "name": "PROPOXYPHENE",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8910191521427315,
          "id": "CHEMBL268254",
          "object": {
            "id": "CHEMBL268254",
            "name": "DELORAZEPAM",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        },
        {
          "score": 0.8901382070795899,
          "id": "CHEMBL1200790",
          "object": null,
          "__typename": "Similarity"
        },
        {
          "score": 0.8850584362001727,
          "id": "CHEMBL3989677",
          "object": {
            "id": "CHEMBL3989677",
            "name": "HYDROCODONE BITARTRATE",
            "__typename": "Drug"
          },
          "__typename": "Similarity"
        }
      ],
      "literatureOcurrences": {
        "count": 336,
        "earliestPubYear": 1975,
        "cursor": "eyJpbmRleCI6MSwic2l6ZSI6MjV9",
        "rows": [
          {
            "pmid": "32206140",
            "pmcid": "PMC7075424",
            "publicationDate": "2020-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "16125625",
            "pmcid": null,
            "publicationDate": "2005-01-12",
            "__typename": "Publication"
          },
          {
            "pmid": "36660119",
            "pmcid": "PMC9843563",
            "publicationDate": "2022-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "34037732",
            "pmcid": "PMC8155824",
            "publicationDate": "2021-05-01",
            "__typename": "Publication"
          },
          {
            "pmid": "21062909",
            "pmcid": null,
            "publicationDate": "2010-11-09",
            "__typename": "Publication"
          },
          {
            "pmid": "35951886",
            "pmcid": null,
            "publicationDate": "2022-08-12",
            "__typename": "Publication"
          },
          {
            "pmid": "21719560",
            "pmcid": "PMC3181429",
            "publicationDate": "2011-10-01",
            "__typename": "Publication"
          },
          {
            "pmid": "31672712",
            "pmcid": "PMC6830717",
            "publicationDate": "2019-10-01",
            "__typename": "Publication"
          },
          {
            "pmid": "36249753",
            "pmcid": "PMC9561887",
            "publicationDate": "2022-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "1097611",
            "pmcid": null,
            "publicationDate": "1975-09-01",
            "__typename": "Publication"
          },
          {
            "pmid": "22492384",
            "pmcid": "PMC3323816",
            "publicationDate": "2012-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "21960542",
            "pmcid": null,
            "publicationDate": "2010-12-29",
            "__typename": "Publication"
          },
          {
            "pmid": "22959419",
            "pmcid": null,
            "publicationDate": "2012-09-05",
            "__typename": "Publication"
          },
          {
            "pmid": "29403350",
            "pmcid": "PMC5786560",
            "publicationDate": "2018-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "20088817",
            "pmcid": null,
            "publicationDate": "2010-03-01",
            "__typename": "Publication"
          },
          {
            "pmid": "20822673",
            "pmcid": null,
            "publicationDate": "2010-09-01",
            "__typename": "Publication"
          },
          {
            "pmid": "33568364",
            "pmcid": "PMC7878138",
            "publicationDate": "2021-02-01",
            "__typename": "Publication"
          },
          {
            "pmid": "16762044",
            "pmcid": "PMC1779399",
            "publicationDate": "2006-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "35520834",
            "pmcid": "PMC9057460",
            "publicationDate": "2020-11-01",
            "__typename": "Publication"
          },
          {
            "pmid": "35464575",
            "pmcid": "PMC8996822",
            "publicationDate": "2022-03-01",
            "__typename": "Publication"
          },
          {
            "pmid": "33192503",
            "pmcid": "PMC7655531",
            "publicationDate": "2020-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "1985650",
            "pmcid": null,
            "publicationDate": "1991-01-01",
            "__typename": "Publication"
          },
          {
            "pmid": "31917418",
            "pmcid": "PMC7139205",
            "publicationDate": "2020-04-01",
            "__typename": "Publication"
          },
          {
            "pmid": "11372804",
            "pmcid": null,
            "publicationDate": "2001-05-01",
            "__typename": "Publication"
          },
          {
            "pmid": "34316417",
            "pmcid": "PMC8287869",
            "publicationDate": "2021-07-01",
            "__typename": "Publication"
          }
        ],
        "__typename": "Publications"
      },
      "__typename": "Drug"
    }
  }
}

```
</details>

**Comment by ireneisdoomed** [comment] 2023-06-22 10:19
This is likely to be caused by the same error we see in https://github.com/opentargets/issues/issues/2971#issuecomment-1602379363

The drug index has duplicates. The ChEMBL IDs @buniello mentions are problematic:
```
In [73]: mol.filter(f.col("id") == "CHEMBL1233").count()
Out[73]: 5

In [74]: mol.filter(f.col("id") == "CHEMBL122").count()
Out[74]: 4
```

**Comment by d0choa** [comment] 2023-06-23 09:49
Resolved in dev for the drugs reported here

**Closed by d0choa** 2023-06-23 09:49 UTC
Labels: Bug, Backend, Frontend, Platform
