### ISSUE TITLE
Invalid entities in PMID:15684057

### ISSUE THREAD

**Issue by ravwojdyla** [opentargets/issues#3053] opened 2023-08-29 18:51 UTC
This is from 23.06 release. It appears there are ~1309 unique entities (gene, disease) coming from https://pubmed.ncbi.nlm.nih.gov/15684057/. This article is about "Fluid-flow-induced flutter of a flag", and seems rather unrelated. Something appears to be off.

Looking up a random 10 examples in the abstract:

Row | entity_id | entity_label | entity_type | entity_span | section |
| -- | -- | -- | -- | -- | --
1 | ENSG00000166819 | PLIN1 | gene | PLIN1 | abstract |  
2 | EFO:0000544 | infection | disease | infection | abstract |  
3 | MONDO:0000473 | arterial disorder | disease | arteriopathy | abstract |  
4 | ENSG00000012223 | LTF | gene | LTF | abstract |  
5 | ENSG00000175084 | DES | gene | desmin | abstract |  
6 | ENSG00000109819 | PPARGC1A | gene | PPARGC1A | abstract |  
7 | ENSG00000047457 | CP | gene | CP | abstract |  
8 | EFO:0000544 | infection | disease | infection | abstract |  
9 | ENSG00000162191 | UBXN1 | gene | UBXN1 | abstract |  
10 | OBI:1110021 | infect | disease | infection | abstract

I can't find any of these in the text of the abstract.

**Comment by DSuveges** [comment] 2023-09-07 09:58
Hi @ravwojdyla,

Thank you for reporting this quite annoying issue. The reason of the seemingly bogus entities, is that the same pmid points to multiple, completely unrelated publications identified by their PMCIDs. In your example 311 of them [1]. We are [aware of this ambiguity](https://github.com/opentargets/issues/issues/2970) for few months now. @tsantosh7 investigated the problem and could confirm that the problem was propagated from EPMC [2], and is in conversation with their database team to resolve the issue. 

Until the problem is resolved at the source, we are planning to drop ambiguous entries from the literature dataset on our side. Thank you again, and please keep reporting any inconsistencies potential problem you might found!

Best,
Daniel



[1] Retrieving the pmc ids associated with `PMID:15684057`:

```python
(
    spark.read.parquet('gs://open-targets-data-releases/23.06/output/etl/parquet/literature/matches')
    .filter(f.col('pmid') == pmid)
    .select('pmid', 'pmcid')
    .distinct()
    .count()
)
```
Gives 311.

[2] The same ambiguity can be reproduced at the EPMC front end as well. An other example is PMID:28656131 which is assigned to PMC5731772 and PMC5478796. You can see these two papers showing up [when searching for the pmid on EPMC](https://europepmc.org/search?query=28656131). However they are showing the correct PMID. In the matches dataset however:

```python
(
    spark.read.parquet('gs://open-targets-data-releases/23.06/output/etl/parquet/literature/matches')
    .filter(f.col('pmid') =='28656131')
    .select('pmid', 'pmcid')
    .distinct()
    .count()
)
```

```
+--------+----------+
|    pmid|     pmcid|
+--------+----------+
|28656131|PMC5478796|
|28656131|PMC5731772|
+--------+----------+
```

Where `PMC5478796` is the correct. Unfortunately we don't have the right PMID for `PMC5731772`.

**Comment by ravwojdyla** [comment] 2023-09-07 11:07
@DSuveges that makes sense! Thanks for the context, this is awesome! I have subscribed to https://github.com/opentargets/issues/issues/2970.

**Comment by prashantuniyal02** [comment] 2023-09-07 11:12
duplicate of #2970

**Comment by prashantuniyal02** [comment] 2023-09-07 11:13
Duplicate of #2970

**Closed by prashantuniyal02** 2023-09-07 11:13 UTC
Labels: Bug, Data, Platform, Literature

**Comment by tsantosh7** [comment] 2023-09-08 08:27
The PMID here in PubMED is 29255720 which is the correct mapping for PMC5731772

![Screenshot from 2023-09-07 16-19-37](https://github.com/opentargets/issues/assets/2648488/63dd0bd3-bf84-4a79-8155-d35da5921eac)

The PMID here in EuropePMC is 29255720 for PMC5731772 (correct)

![Screenshot from 2023-09-07 16-19-15](https://github.com/opentargets/issues/assets/2648488/99d528b3-23a7-4922-a633-152a2ddd6b32)


However when I deal with the raw XML, the mapping for PMC5731772 is showed as 28656131
![Screenshot from 2023-09-07 16-18-25](https://github.com/opentargets/issues/assets/2648488/3292acba-1c10-4f61-8fa6-438846a02346)

After speaking with the Europe PMC project leader and DBA they conveyed that the results were not as anticipated. However, they clarified that they do not have control over the content. For any discrepancies or concerns, contacting NCBI would be the recommended course of action. They also noted that other mapping issues might arise from a variety of different factors. So as a plan of action, we have generated an internal task for looking into this. Unfortunately, we do not have an option to show our tasks publicly as this platform does. Nonetheless, I will keep this thread updated whenever there is an update.

**Comment by ravwojdyla** [comment] 2023-09-08 11:47
@tsantosh7 awesome, thanks for the context, and looking forward to the updates.
