### ISSUE TITLE
Duplicate match entries in Europe PMC evidence

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1560] opened 2021-05-20 16:07 UTC
@gkos-bio noted that there are some duplicate matches in the Europe PMC evidence, particularly with titles of publications that are available with free-text articles. Some examples are below:

https://platform.opentargets.org/evidence/ENSG00000151577/EFO_0000692 - see “Prevalence of polymorphisms in the ANKK1, DRD2, DRD3 genes and metabolic syndrome in refractory schizophrenia.” (scroll to page 3 of results)

![image001](https://user-images.githubusercontent.com/7490258/119012023-8e11f180-b98d-11eb-8e97-54495f893038.jpg)

https://platform.opentargets.org/evidence/ENSG00000146648/MONDO_0008903 - see “TAZ sensitizes EGFR wild-type non-small-cell lung cancer to gefitinib by promoting amphiregulin transcription.”

![Screenshot 2021-05-20 at 15 41 11](https://user-images.githubusercontent.com/7490258/119011930-6de23280-b98d-11eb-9aec-cf4d016b3927.png)

https://platform.opentargets.org/evidence/ENSG00000196415/EFO_0000685 - see “Anti-citrullinated peptide/protein antibody (ACPA)-negative RA shares a large proportion of susceptibility loci with ACPA-positive RA: a meta-analysis of genome-wide association study in a Japanese population.”

Some of the duplicates are true duplicates where the exact same string is matched - see the second and third examples above. In other cases, the duplicate is not technically a duplicate because one of the strings has a punctuation mark while the other one doesn’t - but the same term is matched - see the first example.

**Comment by DSuveges** [comment] 2021-07-16 13:37
When we noticed this issue, I found slight differences between the seemingly duplicated sentences eg. period, comma, special characters.  These differences cannot be resolved upon the generation of the evidence (mostly because the difference in the coordinates). However upon taking over the data from epmc, we can drop the abstracts from full text articles where the same article is available in the abstract pile. As far as I know that was the decision, but could you pease confirm this @mkarmona ?

**Comment by mkarmona** [comment] 2021-07-16 15:43
@DSuveges I will implement it accordingly.

**Comment by prashantuniyal02** [comment] 2023-03-07 15:43
Closing as this is no longer reproducible.

**Closed by prashantuniyal02** 2023-03-07 15:43 UTC
Labels: Bug, Data, Platform
