### ISSUE TITLE
Add more granular "Full Text Available" description from Europe PMC

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#3008] opened 2023-07-03 10:34 UTC
As a user, I want to know whether publications linked in the Open Targets Platform are Free to Read only, or Free to Read and Use.

Full text articles in Europe PMC are [either Free to Read only, or Free to Read and Use](https://europepmc.org/Help#searchcoverFT). Free to Read only articles cannot be mined, and this information might be useful to users of the Open Targets Platform.

I suggest modifying the "Full Text Available" chip for publications to include this information.

**Comment by tsantosh7** [comment] 2023-07-03 10:38
Hi @HelenaCornu I will discuss this with our HelpDesk team and update you.

**Comment by tsantosh7** [comment] 2023-07-03 13:13
Hi @HelenaCornu 

After consulting with our data team (Jags)/Service coordinator, we have confirmed that the Open Targets query used to retrieve articles is hard coded with the condition (AND pm.availability_status='O'). In this context, "O" represents "Open," which signifies that the articles retrieved are both Free to Read and Use. On the other hand, if the availability status were "F," it would indicate that the articles are only Free to Read. Since we specifically use "O" to filter the articles, it ensures that we are selecting only those that are Free to Read and Use.

While it is true that Free to Read only articles cannot be mined, the articles provided for Open Targets Platform are Free to Read and Use. Therefore, they can be mined and utilised for various purposes beyond mere reading.


Note: The articles in the OA subset may not always have a CC BY license. But it contains articles where publishers have agreed they can be text mined and reused. See e.g. https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/ and https://europepmc.org/downloads/openaccess for more information.

**Comment by HelenaCornu** [comment] 2023-07-03 13:24
Thank you for investigating @tsantosh7! I wonder if we are talking about different things, since the Platform does display articles where the full text is not available. 

See for example, if I click on the 8 publications for the first line of evidence in the GEL PanelApp widget for [NOD2 and Crohn's disease](https://platform.opentargets.org/evidence/ENSG00000167207/EFO_0000384), the full text is available for some articles but not others.
![Screenshot 2023-07-03 at 14 22 33](https://github.com/opentargets/issues/assets/73692302/f5e1484c-b85b-45da-bbaa-73313dc0182e)

What I suggest is to indicate, for the articles where the full text is available, whether the publication is Free to Read or Free to Read and Use.

**Comment by tsantosh7** [comment] 2023-07-03 13:38
Hi @HelenaCornu 

Thank you for clarifying. I understand what you mean here and we were talking about different things. I just wanted to be sure that the content that is text mined for entity recognition is indeed free to read and use.

**Comment by d0choa** [comment] 2023-09-05 16:10
@buniello I'm tagging you here. This information is all in the EPMC API response that the @opentargets/fe-team uses. In fact, @carcruz used it to decide whether the buttom will be displayed or not.

What @HelenaCornu is sugessting - flagging wether an article is `free to use` or `free to read and use` would help to understand why the "Show summary" is sometimes there and sometimes not.

**Comment by buniello** [comment] 2023-09-07 14:36
Discussed with the FE team: the current plan is for this task to be prioritised after the 23.09 release and the outcome will be included in a soft release.

**Comment by buniello** [comment] 2023-09-14 09:05
Hi @opentargets/fe-team - following up from the discussion on backlog tickets we had yesterday - this one could be prioritised already

**Comment by LucaFumis** [comment] 2023-09-21 10:03
So should the text "Full text available" be changed to "Free to use" / "Free to read and use"? 
Or something like "Full text available: free to use"...

**Comment by LucaFumis** [comment] 2023-09-21 14:02
The PR has the link with example to see both cases. If the text is too long it can be reworded? Or could perhaps use icons if it makes sense?

**Comment by LucaFumis** [comment] 2023-09-22 15:21
A couple of more options as per chat/PR comments.

Simple shorter text:
<img width="603" alt="Screenshot 2023-09-22 at 16 15 17" src="https://github.com/opentargets/issues/assets/8592363/5ca14aaf-e683-4ac0-a76c-dcb06ea449f0">

Tooltip with standard "?" icon:
<img width="602" alt="Screenshot 2023-09-22 at 13 13 21" src="https://github.com/opentargets/issues/assets/8592363/8fd7f2fd-dbd8-4266-abdc-6812ef9188ab">
<img width="600" alt="Screenshot 2023-09-22 at 13 13 13" src="https://github.com/opentargets/issues/assets/8592363/6940a6d1-09f7-4a36-b59e-fbf117e06467">

Tooltip with possible custom icons:
<img width="601" alt="Screenshot 2023-09-22 at 15 03 19" src="https://github.com/opentargets/issues/assets/8592363/7aa42d9a-891b-49a8-bece-2a8e4100a5a2">
<img width="601" alt="Screenshot 2023-09-22 at 15 01 55" src="https://github.com/opentargets/issues/assets/8592363/aa5eeb75-f934-48fc-9d07-d76f7df7302f">

**Comment by buniello** [comment] 2023-09-25 09:21
Hi @LucaFumis, thanks very much for this! They all look really good, I think my favourite is still first option (simple shorter text) - we just need to add a frame (same as `show abstract` and `show summary` tabs.

**Comment by LucaFumis** [comment] 2023-09-25 21:29
I also like the option with the short text. The other two elements ("Show abstract" and "Show summary") are buttons, so that's why they have the border. The "Full text available" is just info text and is not clickable... so perhaps it's not a bad thing that it looks a little different than the other two? 
It could maybe look like a chip (same as at the top of evidence page)... but also not sure that would be any clearer...

**Comment by buniello** [comment] 2023-09-26 08:11
@LucaFumis - you're right, it is not clickable and therefore good as it is ☺️

**Comment by buniello** [comment] 2023-09-27 09:40
Linking this issue here for more discussion: https://github.com/opentargets/issues/issues/2879

**Comment by prashantuniyal02** [comment] 2023-09-28 09:44
This is what EPMC does on their website:
![image](https://github.com/opentargets/issues/assets/122870584/8b477431-ca9b-400a-a0fa-561173d57d10)
![image](https://github.com/opentargets/issues/assets/122870584/ae62f21d-da83-45d1-9ccb-07dc2c63ed32)

**Closed** 2023-10-19 12:31 UTC
Labels: Enhancement, Platform
