### ISSUE TITLE
Associations on the fly search-box only works on first page of the list

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3179] opened 2023-12-19 18:04 UTC
**Describe the bug**
The associations on the fly target or disease search-box only works on first page of the list.
E.g. searching for `breast cancer` on second page of [this list](https://platform.opentargets.org/target/ENSG00000133703/associations) 
E.g. searching for 'IRF1' on second page [here](https://platform.opentargets.org/disease/MONDO_0005301/associations)

(assigning to myself for now)

**Comment by DSuveges** [comment] 2023-12-19 19:27
I'm sure this behaviour is due to pagination: to save bandwith and to speed up page load the API only returns associatinos in a chunk of 50. The search bar on the top only knows about this 50. If you navigate to the next page, the entires on the previous page is lost, the search function cannot see them, just the newly loaded chunk. 

I think the issue could be addressed by linking the search functionality directly to the API, however not sure how performant that would be.

**Comment by prashantuniyal02** [comment] 2024-01-09 11:42
The issue is that the search result view does not default to the first page.

- Search 'itg' on page 1 [here](https://platform.opentargets.org/disease/MONDO_0005301/associations) -> 14 entries found.
- Move to the second page [51-100] entries and search 'itg' -> no entries found
- However move to the first page and you can see the 14 entries.
![Screenshot 2024-01-09 at 11 24 27](https://github.com/opentargets/issues/assets/122870584/a5ede625-a7b4-409d-bb5b-c2394b0b8dd9)

If you search 'neoplasm' on the second page [here](https://platform.opentargets.org/target/ENSG00000012048/associations), you will see only 4 out of the 54 search results.

**Closed** 2024-03-25 10:00 UTC
Labels: Frontend, Platform
