### ISSUE TITLE
Apparently incorrect tractability precedence for HDAC4

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3286] opened 2024-04-16 10:38 UTC
Reported by user,

> I was using the tractability data to help guide selection of targets ... and noticed a discrepancy for HDAC4 in that the marketed drugs/clinical candidates are flagged (correctly) on the OT and ChEMBL websites but in the tractability section this isn't the case (plus, I am not sure that the number of chembl compounds is correct either). 

HDAC4 target page: https://platform.opentargets.org/target/ENSG00000068024

![image](https://github.com/opentargets/issues/assets/5097586/eb5ce9e8-f419-4793-b5d7-3945c69fbd02)

**Comment by hioannidis** [comment] 2024-05-20 16:35
The changes I made are outlined below:

- Change the full URL in the run_pipeline.py and include the "reviewed" category.

```        full_url = 'https://rest.uniprot.org/uniprotkb/stream?fields=accession%2Cid%2Cprotein_name%2Cgene_primary%2Cgene_synonym%2Cxref_geneid%2Cxref_chembl%2Cxref_bindingdb%2Cxref_drugbank%2Cxref_pharmgkb%2Cxref_pharos%2Cxref_pdb%2Ccc_subcellular_location%2Cft_transmem%2Cft_signal%2Cgo_c%2Creviewed&format=tsv&query=%28proteome:UP000005640%29'```

- Included only reviewed results and where uniprot accession is less than 7 characters.

```        human_proteome.query(" `Entry Name` == `Entry Name` & `Reviewed` == 'reviewed' & Entry.str.len() < 7 ", inplace = True)
        human_proteome = human_proteome.drop(columns = ['Reviewed'])```

Feel free to close this issue as the submission for 24.06 is complete and reopen it if there are more issues.

**Comment by ireneisdoomed** [comment] 2024-05-28 10:18
The issue is solved with the latest submission. Thank you for the fix @hioannidis!
I'll keep this open to double check in the FE

**Comment by prashantuniyal02** [comment] 2024-06-18 13:32
This has been resolved in the latest dev version and will be fixed with the Platform 24.06 release.


![Image](https://github.com/opentargets/issues/assets/122870584/8b804b76-787a-43e7-a88b-fd5db250e352)

**Closed by prashantuniyal02** 2024-06-18 13:32 UTC
Labels: Bug, Data, Platform, Data providers
