### ISSUE TITLE
Update obsoleted target annotation query from playground

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3043] opened 2023-08-21 10:55 UTC
API has changed and the target annotation query does not work.

target > tractability > id

is now

target > tractability > label

<img width="1498" alt="Screenshot 2023-08-21 at 11 23 35" src="https://github.com/opentargets/issues/assets/5097586/16f7d672-10e9-4835-82ab-67d7df5147b8">

**Comment by buniello** [comment] 2023-08-21 13:47
<details>
  <summary>Correct API query</summary>

```
query targetAnnotation {
  target(ensemblId: "ENSG00000169083") {
    id
    approvedSymbol
    tractability {
      modality
      label
      value
    }
    safetyLiabilities {
      event
      eventId
      biosamples {
        cellFormat
        cellLabel
        tissueLabel
        tissueId
      }
      effects {
        dosing
        direction
      }
      studies {
        name
        type
        description
      }
      datasource
      literature
    }
  }
}
```
</details>

@chinmehta could you please replace the existing `target annotation` example query with the correct one above

**Comment by fedde-s** [comment] 2023-08-22 07:22
I just found this, checked whether it was already being tracked here and found that it was… since yesterday :joy:

**Comment by d0choa** [comment] 2023-08-22 08:34
@opentargets/fe-team testing would really help with these kinds of things

**Comment by carcruz** [comment] 2023-09-25 15:48
I can confirm that it is merged on the latest `main`

**Comment by prashantuniyal02** [comment] 2023-09-27 15:08
Hi @fedde-s , just wanted to inform you that this has been resolved in the latest Platform 23.09 release. Hence closing the issue.

**Closed by prashantuniyal02** 2023-09-27 15:08 UTC
Labels: Bug, Frontend, Platform

**Comment by fedde-s** [comment] 2023-10-03 13:28
Sorry for my delayed reply—I can also confirm that it's fixed, even when running the code outside of EBI's infrastructure :smile:

Nice and tidy!
