### ISSUE TITLE
Improvements on new EPMC pipeline output

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#1367] opened 2021-01-28 16:38 UTC
Including here for discussion and future reference.

The output currently generated (20.09) follows the next schema:

```
 |-- organisms: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- pmid: string (nullable = true)
 |-- pubDate: string (nullable = true)
 |-- sentences: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- co-occurrence: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- association: struct (nullable = true)
 |    |    |    |    |    |-- Altered Expression: double (nullable = true)
 |    |    |    |    |    |-- Any: double (nullable = true)
 |    |    |    |    |    |-- Genetic Variation: double (nullable = true)
 |    |    |    |    |    |-- Negative: double (nullable = true)
 |    |    |    |    |    |-- Neutral: double (nullable = true)
 |    |    |    |    |    |-- No: double (nullable = true)
 |    |    |    |    |    |-- Positive: double (nullable = true)
 |    |    |    |    |    |-- Regulatory modification: double (nullable = true)
 |    |    |    |    |    |-- Yes: double (nullable = true)
 |    |    |    |    |-- end1: long (nullable = true)
 |    |    |    |    |-- end2: long (nullable = true)
 |    |    |    |    |-- evidence_score: long (nullable = true)
 |    |    |    |    |-- label1: string (nullable = true)
 |    |    |    |    |-- label2: string (nullable = true)
 |    |    |    |    |-- relation: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- endr: long (nullable = true)
 |    |    |    |    |    |    |-- labelr: string (nullable = true)
 |    |    |    |    |    |    |-- startr: long (nullable = true)
 |    |    |    |    |    |    |-- typer: string (nullable = true)
 |    |    |    |    |-- start1: long (nullable = true)
 |    |    |    |    |-- start2: long (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
 |    |    |-- matches: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- endInSentence: long (nullable = true)
 |    |    |    |    |-- label: string (nullable = true)
 |    |    |    |    |-- sectionEnd: long (nullable = true)
 |    |    |    |    |-- sectionStart: long (nullable = true)
 |    |    |    |    |-- startInSentence: long (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
 |    |    |-- section: string (nullable = true)
 |    |    |-- text: string (nullable = true)
```

After discussion in the OT team we have the next suggestions for improvements:

- We are going for the ML pipeline in the first place. Since our grounding is based on dictionaries, we don't see a value on having 2 dictionary-based steps. All checks we performed so far indicate good results with ML + dictionary grounding. 

- The current `section` field contains the title of the section. We suggest renaming it to `sectionTitle` and could be `null` if we don't have access to the text.

  ```
  >>>epmc.select(explode(col("sentences.section")).alias("section")).distinct().show(5, truncate = False)
  +------------------------------------------------+
  |section                                         |
  +------------------------------------------------+
  |Amplification and sequencing analysis of pfmsp-3|
  |Outside/in stresses and serum cTnI and cTnT     |
  |Histological study                              |
  |Postresuscitation Management                    |
  |Lopinavir–ritonavir                             |
  +------------------------------------------------+
  only showing top 5 rows
  ```

-  However, we are missing information as the field is not abstracting which section of the manuscript the sentence is (e.g. introduction, results, etc.). We will need this information for the scoring. Would it be possible to have a `section` field containing an enum similar to the options the old pipeline produced. See next:

  ```
  >>> oldEvd.filter(col("sourceID") == "europepmc").select(explode(col("evidence.literature_ref.mined_sentences")).alias("sentence")).select(col("sentence.section").alias("section")).groupBy("section").count().show(truncate = False)
  +---------------------------+-------+
  |section                    |count  |
  +---------------------------+-------+
  |case_study                 |17837  |
  |title                      |1184291|
  |table                      |258976 |
  |conclusion_and_future_work |173492 |
  |other                      |2530869|
  |figure                     |406341 |
  |appendix                   |6860   |
  |discussion                 |2078112|
  |introduction_and_background|1093167|
  |results                    |1474558|
  |abstract                   |7132481|
  +---------------------------+-------+
  ```

- `evidence_score` won't be necessary. A single evidence in the platform is formed by the aggregation of all sentences mentioning same target and same disease in the same paper. Since this requires grounding, we will do this on our side. However, we will need the logic of the old scoring scheme, in order to move it to a downstream process. Could EPMC team please share this with us?. We will need this information in order to phase out the old pipeline, but we expect the scoring to be improved in the future.

-  `pubDate` not sure what's the specification of this field but it contains dates in the future. For example,  https://pubmed.ncbi.nlm.nih.gov/32265214/  is dated in 2022-04-06, which seems to be when the article will be accessible for open access. We need a more realistic date around when the manuscript was made public.

- `pmid` currently contains PMC ids. Is it possible to have a field containing PMIDs (integer values) named `pmid` and another named `pmcid` containing the PMC ids when available?

  ```python
  >>> epmc.select("pmid").show(5)
  +----------+
  |      pmid|
  +----------+
  |PMC7235531|
  |PMC7235532|
  |PMC7235536|
  |PMC7235537|
  |PMC7235538|
  +----------+
  only showing top 5 rows
  ```

- It would be ok if the field `text` is not available for matches, .

**Comment by tsantosh7** [comment] 2021-02-05 10:51
Thank you @d0choa 
Here is what I have gathered from your analysis.

1, 2, 4, 6 are straightforward and 3, 5 can be accommodated after some unit testing.

`1. ML output`
`2. section => sectionTitle (nullable)`

```
3. sectionTitles to reflect one of the following:
case_study  
title
table 
conclusion_and_future_work 
other 
figure
appendix
discussion 
introduction_and_background
results
abstract  
```
`4. No need for evidence scoring`

`5. pubDate fixing`

`6. pmid to be renamed to pmcid for FT articles`

**Comment by d0choa** [comment] 2021-03-05 14:54
hi @tsantosh7! we have 3 other (hopefully) simple comments that came out as part of re-implementation of the old pipeline scoring. @DSuveges can provide more details if necessary.

- The fields `sectionEnd` and `sectionStart` refer to the position where the sentence start/end within the section. At the moment, it's nested inside matches, when in fact it would make more sense to specify it only once per sentence. Could you move this field at that level to avoid unnecessary repetitions?

- The fields `sectionStart` and `sectionEnd` are sometimes present and sometimes absent. Could you remind us if there is a reason for this?

- Could we add another field named `sectionLength` at the sentence level that specifies the total length of the current section. This way, we can know that if sectionEnd == sectionTotal we are in the last sentence of the section.

**Comment by tsantosh7** [comment] 2021-03-05 15:33
@d0choa I will look into this and come back to you by next working day.

**Comment by DSuveges** [comment] 2021-03-12 08:44
Hi @tsantosh7, I'm wondering how things are going? We now have the script ready to generate target/disease evidence strings for the platform based on the new cooccurrences file, but the only thing is missing is the scoring. To implement that on our side we'll need the bits on @d0choa's above comments. The 21.04 release is going to be special as this will be the first release when we are migrating to the new evidence schema, that's whey we are very keen to make sure everything works and want to put everything in place well in time to have chance to fix unforeseeable bug that might occur.

**Comment by tsantosh7** [comment] 2021-03-12 10:23
Hi @DSuveges. We will start preprocessing the work this Monday. It might take a week to process all the articles. So we are ideally looking at March 21 earliest to submit you the new annotations.

**Comment by tsantosh7** [comment] 2021-03-12 11:54
@d0choa @DSuveges 

`The fields sectionEnd and sectionStart refer to the position where the sentence start/end within the section. At the moment, it's nested inside matches, when in fact it would make more sense to specify it only once per sentence. Could you move this field at that level to avoid unnecessary repetitions?`

Sure, I can move this up to a higher level (sentence level). 

`The fields sectionStart and sectionEnd are sometimes present and sometimes absent. Could you remind us if there is a reason for this?`

If the sentences come from an abstract section then only we would use these otherwise they are nullable.

`Could we add another field named sectionLength at the sentence level that specifies the total length of the current section. This way, we can know that if sectionEnd == sectionTotal we are in the last sentence of the section.`

Ofcourse we could add this.

**Comment by DSuveges** [comment] 2021-03-18 15:31
There was an issue with the publication [PMC5654964](https://europepmc.org/article/MED/29066806?singleResult=true): the identified  target entity was `( `I noticed when I was checking the evidences I created based on the cooccurrence file. 

@mkarmona took a look and told that publication even breaks grep on the command line. His suspicion is that there might be an escaping issue. Could you please take a look at it: `NMP_Annot_PMC5652480_PMC5667274_split_3.json` in this file he found the issue.

**Comment by saha-shyamasree** [comment] 2021-03-18 18:01
@d0choa : On your comment 'Could we add another field named sectionLength at the sentence level that specifies the total length of the current section. This way, we can know that if sectionEnd == sectionTotal we are in the last sentence of the section.' May I ask you why you want to check that conditions, please? 
@DSuveges : I am taking care of some of these requests. Do you want me to do the Target-Disease-PMID level evidence score for you? It will be fairly easy for me to implement.

**Comment by saha-shyamasree** [comment] 2021-03-18 18:02
> There was an issue with the publication [PMC5654964](https://europepmc.org/article/MED/29066806?singleResult=true): the identified target entity was `( `I noticed when I was checking the evidences I created based on the cooccurrence file.
> 
> @mkarmona took a look and told that publication even breaks grep on the command line. His suspicion is that there might be an escaping issue. Could you please take a look at it: `NMP_Annot_PMC5652480_PMC5667274_split_3.json` in this file he found the issue.

I will look into that and fix the bug if any.

**Comment by DSuveges** [comment] 2021-03-22 16:02
@saha-shyamasree 

> May I ask you why you want to check that conditions, please?

So we would like to reproduce the scoring described in Kafkas et al. That method takes into consideration where the identified sentence is located within a section. Specifically, it matters if a sentence is in the first, second or the last sentence of an abstract. At the moment we have no means to infer this. That’s the point of this request. 

> Do you want me to do the Target-Disease-PMID level evidence score for you? It will be fairly easy for me to implement.

Also yes, please keep adding the evidence score.

**Comment by saha-shyamasree** [comment] 2021-03-23 11:11
1. Publication date has been fixed. 
2. I propose we keep both the PMC and the PMID when available to facilitate filtering out abstracts of the full text articles from the abstract set.
3. Section titles are now sorted and is in the format of previous version.
I am working on the target-disease-pmid/pmcid score and moving the sectionStart and sectionEnd to the upper level.

**Comment by DSuveges** [comment] 2021-03-23 11:55
@saha-shyamasree, having both PMC and PMID is good, but could you please add PMID regardless the availability of the full text? We use PMID to generate link on our frontend and having a PMC id breaks the validation. Thank you so much!

**Comment by saha-shyamasree** [comment] 2021-03-23 13:07
> @saha-shyamasree, having both PMC and PMID is good, but could you please add PMID regardless the availability of the full text? We use PMID to generate link on our frontend and having a PMC id breaks the validation. Thank you so much!

done now

**Comment by saha-shyamasree** [comment] 2021-03-23 20:24
sectionStart and sectionEnd is now at a higher level.

**Comment by saha-shyamasree** [comment] 2021-03-25 09:31
@DSuveges , @d0choa : I just occured to me that without the normalizing the entity terms to a db id we can not correctly compute the score. So yes it has to happen at your end. Although, if I assume you output the same json format from your normalization script/code, and add the 'db_id' under the 'matches', I can easily compute the score. Does that work for you guys? Please et me know ASAP as everything else is done.

**Comment by DSuveges** [comment] 2021-05-26 16:13
These were our questions sent over on 24th May. Based on @saha-shyamasree's response some of the items are already fixed:

- [x]  Currently publication date (pubDate) is not standard/consistent. Something like yyyy-MM-dd would be great. Also do you think there’s anything you can do about publications, which date to the future?

- [x]  At the moment PMCID or PMID are exclusive in the submitted dataset. When papers have both PMID and PMCID, we would like to have both.

- [x]  Due to the nestedness of the directories in the google bucket, ingesting the input files is quite problematic at the moment. Ideally, directories should contain directories or files, but not both mixed together.

- [ ]   Duplications causes issues (e.g. when data is processed through full text and abstract). We propose to drop the publications from abstract when there is a full text available. Later on, we can evaluate if this causes any issues. 

@saha-shyamasree 's comment:
```
I am thinking if it will be better to do it on your side, as you are doing a pass on the data during normalizing the terms to a DB id. Plus, you will access to the whole thing, if you find excluding those abstracts create issue, you can revert to existing system.
```

- [ ]   We were wondering if you could improve the sentensizer to reduce the number of overly long sentences.

- [ ]   Under #1367 - There was an issue with the publication PMC5654964, we were wondering if you could take a look at that.

@saha-shyamasree 's comment:
```
I will check the publication next week and let you know.
```

**Comment by d0choa** [comment] 2021-05-26 16:15
There is a systematic problem with encodings in the processing of full-text articles.

The next is just an example:

```
## Full text
❯ gsutil cat gs://otar025-epmc/21.04/epmc-08-04-2021/NMP_SEC_PMC3900032_PMC3909995.jsonl | jq 'select(.pmcid == "PMC3902282")' | jq '.sentences[] | select(.section == "title") | .text'
"Habenular expression of rare missense variants of the Î24 nicotinic receptor subunit alters nicotine consumption"

## Medline
❯ gsutil cat gs://otar025-epmc/21.04/epmc-08-04-2021/ML/NMP_Annot_medline.24477000.jsonl  | jq 'select(.pmid == "24478678")' | jq '.sentences[] | select(.section == "title") | .text'
"Habenular expression of rare missense variants of the β4 nicotinic receptor subunit alters nicotine consumption."
```

To give a sense of the magnitude of the problem, we found 57,798 matches of `Alzheimer's disease` in 30,410 different publications that we couldn't normalise because of the wrong encoding of the `'` symbol.

**Comment by d0choa** [comment] 2021-05-27 08:51
Apart from the very long sentence problem reported by @DSuveges due to incorrect sentence splitting, @mkarmona also reported this can create artificial labels:

```
-RECORD 0-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 pmid            | 32497751                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 pmcid           | PMC7832808                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 pubDate         | 01/07/2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 date            | 2020-07-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 year            | 2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 month           | 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 day             | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 organisms       | [virus, coronavirus, human]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 section         | other                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 text            | If complex reconstructive procedures are required to preserve patient's functioning and long-term survival, considerations regarding decisions, estimated operative times, length of hospital stay, and the current situation of hospital resource shortage should be carefully planned.Salivary gland cancerSalivary duct carcinomaHigh-grade mucoepidermoid carcinomaAdenoid cystic carcinomaCarcinoma ex pleomorphic adenomaOther high-grade salivary cancerLow-grade salivary carcinoma:Acinic cell carcinomaBasal cell adenocarcinomaCystadenocarcinomaSpecific considerations for salivary gland tumors-Consider surgery in the first place for high-grade salivary cancer including:âSalivary duct carcinomaâHigh-grade mucoepidermoid carcinomaâCarcinoma ex pleomorphic adenomaâAcinic cell carcinomaâOther high-grade salivary cancer -In the very strained service for cancer surgery, neoadjuvant radiotherapy might be considered. 
 trace_source    | gs://ot-snapshots/otar025-epmc/20210408/NMP_SEC_PMC7830001_PMC7840000.jsonl                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 endInSentence   | 328                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 label           | Salivary gland cancerSalivary duct carcinomaHigh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 sectionEnd      | null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 sectionStart    | null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 startInSentence | 280                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 type            | DS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 keywordId       | null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 isMapped        | false
 ```
 
 Looking at the specific example, sentences are not split based on the glyphs and that causes artificially long sentences and labels.  
 
<img width="642" alt="Screenshot 2021-05-27 at 09 48 25" src="https://user-images.githubusercontent.com/5097586/119795815-bab79300-bed0-11eb-844b-2b1a31dc317a.png">

**Comment by d0choa** [comment] 2021-05-28 15:52
Following up on the conversation this morning and the question from @tsantosh7.

There were no encoding issues in the full-text processing of the test set (September 2020). At least not for the example provided above.

```
❯ gsutil cat 'gs://otar025-epmc/dev_newpipeline/NP20.09/NMP_FT20.09/NMP_Annot_PMC3887316_PMC3905223_split_*.jsonl' | jq 'select(.pmid == "PMC3902282") | .sentences[] | select(.section == "title") | .text'
"Habenular expression of rare missense variants of the β4 nicotinic receptor subunit alters nicotine consumption"
```

**Comment by DSuveges** [comment] 2023-01-20 15:36
I would close this ticket for now. Upon re-running the literature pipeline we can continue the investigation and open new tickets if new problems are identified.

**Closed by DSuveges** 2023-01-20 15:36 UTC
Labels: Platform
