### ISSUE TITLE
Changes in molecular interactions (Intact) data model

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3038] opened 2023-08-14 16:28 UTC
Can we confirm this will cause no issues in the future and come back to Intact if so?

> Hi All,
> 
> We have added a new file ‘interactor_pair_interactions_new_format.json’ to the files with the data from last release in http://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/. This file contains the same interactions as the ‘interactor_pair_interactions.json’ file, with the addition of new fields for the host organism tissue in each interaction. For the next release we plan to replace the ‘interactor_pair_interactions.json’ file with the new one, so please let us know if this change is ok for you.
> 
> Thanks & Regards,
> IntAct Developers
>

**Comment by DSuveges** [comment] 2023-08-17 10:46
For this release it cannot cause any problem, because the file picked up by PIS follows the old schema. However the schema change is quite minimal:

**the schema of the new field:**

```json
{
  "full_name": "Breast cancer tissue",
  "short_name": "breast_cancer",
  "xrefs": ["UBERON:0000310"]
}
```
It's rarely populated (0.5%). At this point, I assume, we can just ignore it, I assume, if we are not explicitly ask for this field, it will be excluded from the output and would not be exposed. But someone from the backend team could confirm. Also, again, it is an issue from the next release.

**Comment by prashantuniyal02** [comment] 2023-08-22 14:11
Duplicate of #3032

**Closed** 2023-08-22 14:17 UTC
Labels: Data, PIS, ETL, Platform
