### ISSUE TITLE
Upgrade Play Framework to it's latest version

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3329] opened 2024-06-03 13:11 UTC
As a **developer** I want **update the Play Framework version** because **current version no longer has support**

## Background

The current version of Play Framework used in the [API](https://github.com/opentargets/platform-api) is 2.8 and this version [stopped receiving updates](https://www.playframework.com/documentation/3.0.x/General#End-of-life-(EOL)-Dates) 31st of May 2024. The latest version is [3.0](https://www.playframework.com/documentation/3.0.x/Home). We need to be specially careful with the move from Akka Http to Apache Pekko, this is detailed in the [migration guide](https://www.playframework.com/documentation/3.0.x/Migration30).

## Tasks

- [ ] Update the latest version of the Play Framework.
- [ ] Test API is not affected by the update.

## Acceptance tests

How do we know the task is complete? 

1. When the sbt file points to version 3.x and the API runs correctly.
2. When we use the API and the resulting data is the same as it was before the update.

**Comment by prashantuniyal02** [comment] 2024-09-10 08:31
Duplicate of #3419

**Closed by prashantuniyal02** 2024-09-10 08:31 UTC
